-- ---------------------
-- 基本配置
-- ---------------------

-- 当前上传存储路径
CurrentPath: \pet-food-stroe\image
-- default : \项目名称 (遵守文件夹创建原则)\image
-- CurrentPath: \sky-take-out\image


-- 1. 是否允许 文件覆盖
-- default : ture
FileOverlay: false

-- 2. 文件上传后的 返回类型
-- 1. 原文件	2. 8 code		3. 12 code	4. 12 code 有序uuid	5. 有序 uuid	6. 无序 uuid
-- default : 3
FileUploadResultType: 5

-- 3. 是否需要 文件前缀
-- default : false
IsFilePrefix: true

-- 4. 文件前缀类型
-- default : url
FilePrefix: 1

-- 5. 文件前缀类型


-- 配置文件基本说明
SettingSource: default
